### ISSUE TITLE
Issue:  1.12-1.2.0 crashes dedicated server Forge 1.12 build 2400

### ISSUE THREAD

**Issue by kreezxil** [MinecraftModDevelopmentMods/MetalCrops#2]
Notes:
     on startup

crash report:
https://gist.github.com/f3651be63f0ded5d946817e8dc113b55

fml server latest:
https://gist.github.com/ec3851f0250b684e4379211a94399a9c

**Comment by DatrixTHLK** [comment]
Can Verify Client-Side
Crash Report: https://gist.github.com/DatrixTHLK/49e45c551297a942dd87b5fcd4f9a153

Minecraft 1.12
Forge 14.21.1.2405
Metallic Crops 1.2.0

**Comment by knoxhack** [comment]
should be fixed
